//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Restaurent_BOEntities : DbContext
    {
        public Restaurent_BOEntities()
            : base("name=Restaurent_BOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_area> tbl_area { get; set; }
        public DbSet<tbl_city> tbl_city { get; set; }
        public DbSet<tbl_country> tbl_country { get; set; }
    }
}
