//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_country
    {
        public string country_name { get; set; }
        public string status_value { get; set; }
        public long country_id { get; set; }
        public string cur_pair { get; set; }
    }
}
